name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: self-hosteda

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/

    - name: Start Minikube cluster
      run: |
        minikube stop 
        minikube start --driver=docker 

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker-compose down
        docker-compose up -d
        docker tag devops-fullstack-app-frontend:v1 ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-frontend:v1
        docker tag devops-fullstack-app-backend:v1 ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-backend:v1
        docker tag postgres:13 ${{ secrets.DOCKER_USERNAME }}/postgres:13
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-frontend:v1
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-backend:v1
        docker push ${{ secrets.DOCKER_USERNAME }}/postgres:13
        docker-compose down

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/frontend-deployment.yaml  
        kubectl apply -f kubernetes/backend-deployment.yaml
        kubectl apply -f kubernetes/postgres-deployment.yaml

    - name: Port-forward after pods are ready
      run: |
        sleep 120
        chmod +x kubernetes/deploy.sh
        ./kubernetes/deploy.sh

    - name: Verify deployment
      run: |
        kubectl get pods
