name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Adjust file permissions
      run: |
        sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/tech/tech

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker-compose down
        docker-compose up -d
        docker tag devops-fullstack-app-frontend ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-frontend
        docker tag devops-fullstack-app-backend ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-backend
        docker tag postgres:13 ${{ secrets.DOCKER_USERNAME }}/postgres:13
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-fullstack-app-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/postgres:13
        docker-compose down

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/

    - name: Start Minikube cluster
      run: |
        minikube stop 
        minikube delete
        minikube start --driver=docker 

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/frontend-deployment.yaml
        kubectl apply -f kubernetes/backend-deployment.yaml
        kubectl apply -f kubernetes/postgres-deployment.yaml

    - name: Create deploy service
      run: |
          sudo bash -c 'cat <<EOF > /etc/systemd/system/deploy.service
          [Unit]
          Description=Run deploy.sh script

          [Service]
          ExecStart=/home/ubuntu/actions-runner/_work/tech/tech/kubernetes/deploy.sh
          WorkingDirectory=/home/ubuntu/actions-runner/_work/tech/tech/kubernetes/
          Restart=always
          User=${USER}
          Environment=PATH=/usr/bin:/usr/local/bin

          [Install]
          WantedBy=multi-user.target
          EOF'

      # Reload systemd manager configuration
    - name: Reload systemd
      run: sudo systemctl daemon-reload

      # Enable and start the deploy service
    - name: Enable and start deploy service
      run: |
          sudo systemctl enable deploy.service
          sudo systemctl start deploy.service

    - name: Verify deployment
      run: |
        kubectl get pods
