name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t myapp-frontend ./frontend
        docker build -t myapp-backend ./backend
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag myapp-frontend $DOCKER_USERNAME/myapp-frontend
        docker tag myapp-backend $DOCKER_USERNAME/myapp-backend
        docker push $DOCKER_USERNAME/myapp-frontend
        docker push $DOCKER_USERNAME/myapp-backend

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/

    - name: Start Minikube cluster
      run: |
        sudo minikube start --vm-driver=none --kubernetes-version=stable

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/deployment.yaml

    - name: Verify deployment
      run: |
        kubectl get pods --namespace=default
